export const passages = {
  easy: [
    "The sun rises every morning and sets every evening. Birds sing in the trees and dogs play in the park. Life is simple and full of joy when you take time to notice the small things around you.",
    "I like to drink coffee in the morning. It helps me wake up and feel ready for the day. Sometimes I add milk and sugar to make it taste better. Coffee is my favorite drink.",
    "The cat sat on the mat and looked out the window. It was a sunny day and the birds were flying in the sky. The cat wanted to go outside but the door was closed.",
    "She walked to the store to buy some bread and milk. The store was not far from her house. She paid for her things and walked back home. It was a nice day for a walk.",
    "My dog loves to play fetch in the park. He runs fast and brings the ball back every time. We go to the park every evening after dinner. It is our favorite time of the day.",

    "The rain started falling while we were playing outside. We ran back home and watched the storm from the window. After some time, a rainbow appeared in the sky.",
    "Every weekend my family visits my grandmother. She makes delicious food and tells funny stories about her childhood. I always enjoy spending time with her.",
    "Tom forgot his umbrella at school yesterday. Today it rained heavily, so he had to run home quickly. By the time he reached home, all his clothes were wet.",
    "The little boy built a sandcastle near the beach. Waves slowly came closer and washed part of it away. He laughed and started building another one.",
    "Sarah enjoys reading books before going to sleep. Adventure stories are her favorite because they make her imagine exciting places and brave heroes."
  ],

  medium: [
    "The invention of the internet changed the way people communicate and share information. Within a few decades, it became an essential part of daily life for billions of people around the world. Today, it connects businesses, governments, and individuals in ways that were unimaginable just a generation ago.",
    "Learning a new language takes time and consistent effort. You must practice speaking, reading, and writing every single day to make real progress. The most effective learners immerse themselves in the language by watching films, reading books, and speaking with native speakers whenever possible.",
    "Climate change is one of the most pressing challenges facing humanity today. Rising temperatures, melting ice caps, and extreme weather events are already affecting communities around the world. Scientists agree that immediate action is needed to reduce carbon emissions and transition to clean energy sources.",
    "Regular exercise has been proven to improve both physical and mental health. Even thirty minutes of moderate activity each day can reduce the risk of heart disease, improve sleep quality, and boost mood. Many doctors now consider physical activity to be one of the most powerful medicines available.",
    "The human brain is capable of remarkable things. It can process enormous amounts of information, form complex thoughts, and adapt to new situations with surprising speed. Scientists are still working to understand how memory, creativity, and consciousness actually work inside this three pound organ.",

    "Artificial intelligence is transforming industries across the globe. From healthcare and finance to education and entertainment, machine learning systems are helping organizations automate tasks and make better decisions. However, experts continue to debate the ethical implications of rapidly advancing AI technologies.",
    "Space exploration has always inspired human curiosity and ambition. Modern telescopes and spacecraft now allow scientists to study distant planets, black holes, and galaxies with incredible precision. Many researchers believe that future missions could eventually uncover evidence of life beyond Earth.",
    "Time management is an essential skill for students and professionals alike. People who organize their schedules effectively are often more productive and experience less stress. Setting priorities and avoiding distractions can significantly improve focus and efficiency throughout the day.",
    "Social media platforms have dramatically changed the way people interact with one another. While these platforms make communication faster and more convenient, they can also contribute to misinformation and reduced attention spans. Finding a healthy balance between online and offline life is becoming increasingly important.",
    "The history of transportation reflects humanity's constant desire for progress and innovation. From horse drawn carriages to electric vehicles and high speed trains, advancements in transportation technology have continuously reshaped economies and societies around the world."
  ],

  hard: [
    "The archaeological expedition unearthed artifacts that complicated prevailing theories about Bronze Age trade networks. Obsidian from Anatolia, lapis lazuli from Afghanistan, and amber from the Baltic—all discovered in a single Mycenaean tomb—suggested commercial connections far more extensive than previously hypothesized. We've underestimated ancient peoples' navigational capabilities and their appetite for luxury goods, the lead researcher observed.",
    "Quantum entanglement describes a phenomenon whereby two particles become correlated in such a way that the quantum state of each cannot be described independently of the other, regardless of the distance separating them. Einstein famously dismissed this as spooky action at a distance, yet subsequent experiments have consistently validated the effect, fundamentally challenging classical notions of locality and causality.",
    "The epistemological foundations of scientific inquiry rest upon a delicate balance between empirical observation and theoretical framework. Thomas Kuhn's landmark work argued that scientific progress does not occur through gradual accumulation of knowledge, but rather through periodic paradigm shifts—revolutionary transformations in which entire conceptual frameworks are abandoned in favour of fundamentally incompatible successors.",
    "Neuroplasticity research has fundamentally transformed our understanding of the adult brain. Contrary to long-held assumptions that neural architecture becomes fixed after childhood, contemporary neuroscience demonstrates that synaptic connections continuously reorganize in response to experience, learning, and injury throughout an individual's lifespan, opening promising therapeutic avenues for neurological rehabilitation.",
    "The geopolitical ramifications of artificial intelligence development extend far beyond technological competition. Nations that achieve dominance in machine learning infrastructure will likely gain substantial advantages in economic productivity, military capability, and intelligence gathering. Consequently, AI governance has emerged as one of the most consequential and contentious domains of contemporary international relations.",

    "Macroeconomic instability frequently arises from a confluence of interconnected factors, including inflationary pressures, fluctuating interest rates, and disruptions within global supply chains. Policymakers must therefore navigate an exceptionally complex landscape in which short term interventions can produce unintended long term consequences for economic growth and employment.",
    "The philosophical doctrine of existentialism emphasizes individual freedom, personal responsibility, and the search for meaning within an inherently indifferent universe. Thinkers such as Jean Paul Sartre and Albert Camus explored the tension between human aspiration and existential uncertainty through both philosophical essays and literary works.",
    "Advancements in genetic engineering have introduced unprecedented possibilities within modern medicine and agriculture. Technologies such as CRISPR Cas9 enable scientists to modify DNA sequences with remarkable precision, raising profound ethical questions regarding human enhancement, biodiversity, and the long term implications of genomic intervention.",
    "Cybersecurity experts continually warn that modern digital infrastructure remains vulnerable to increasingly sophisticated attacks. State sponsored hacking groups, ransomware organizations, and coordinated misinformation campaigns exploit weaknesses in software systems and human behavior alike, demonstrating that technological advancement often generates new categories of risk alongside innovation.",
    "Theoretical physicists attempting to reconcile general relativity with quantum mechanics have proposed numerous frameworks, including string theory and loop quantum gravity. Despite decades of research, a universally accepted theory of quantum gravity remains elusive, underscoring the profound conceptual challenges involved in describing the fundamental structure of reality."
  ],
};